### ISSUE TITLE
Bypassing Filtering in Iran using VPS

### ISSUE THREAD

**Issue by nvdomidi** [Null3rror/OpenVPN-over-Proxy#4]
Dear Sepehr,

Thank you for your fantastic work. Regarding the current filtering situation in Iran, do you think bypassing DPI would be enough to access internet? I have rented a VPS and tried both using normal OpenVPN, and your DPI bypassing method, however both don't work. Do you have any idea how it would be possible to connect using OpenVPN or another method?

Best,
Navid

**Comment by Null3rror** [comment]
Hi Navid,

It depends on your IPS. Most of them have blacklisted lots of IPs.
As far as I know, they can only detect handshake packets, so if you stay connected, they can't stop you from accessing your VPS.

Things you can do:
1. Get a VPS in Iran and use it as a proxy for your other VPS. (not worth the effort, check 2nd method)
2. Join ProtonVPN's beta in Google Play and use its new Stealth mode protocol. Then create a proxy server on your phone (which is connected to ProtonVPN), then connect other devices (proxy clients) to your phone (proxy server).
In order to set up a proxy server on your phone, download EveryProxy.

**Comment by Null3rror** [comment]
But the only issue with 2nd method is that you need a VPN to login/signup to ProtonVPN
